import { Ubuntu } from 'next/font/google'
import './globals.css'
import ReduxProvider from '@/redux/Provider'
import { Toaster } from 'react-hot-toast'

const ubuntu = Ubuntu({ subsets: ['latin'] , weight:['300','400','500','700']})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={ubuntu.className}>
        <ReduxProvider>
          {children}
          <Toaster
            position="top-center"
            reverseOrder={false}
            gutter={8}
            containerClassName=""
            containerStyle={{}}
            toastOptions={{
              // Define default options
              className: '',
              duration: 5000,
              style: {
                background: '#363636',
                color: '#fff',
              },
    
              // Default options for specific types
              success: {
                duration: 3000,
                theme: {
                  primary: 'green',
                  secondary: 'black',
                },
              },
            }}
          />
        </ReduxProvider>
      </body>
    </html>
  )
}
